name: Issue Handler

on:
  issues:
    types: [opened, edited]

jobs:
  tag-and-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Tag and Assign Issue
      uses: actions/github-script@v6
      with:
        script: |
          const issue_number = context.issue.number;
          const message = 'Thank you for submitting an issue. We will review it as soon as possible.';

          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            labels: ['NEW!']
          });

          await github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            assignees: ['ancharbo']
          });

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            body: message
          });
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}